version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=my-site-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend-vue:
    build: frontend-vue
    depends_on:
      - infra
    volumes:
      - ./frontend-vue:/code
      - /code/node_modules
      - ./.cdk-out:/output
    command: npm run serve
    ports:
      - 8081:8080
    working_dir: /code
  infra:
    build: infra
    depends_on:
      - localstack
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - LOCALSTACK_HOST=localstack
    env_file:
      - .env
    command: ./deploy.sh
    working_dir: $PWD/infra
    volumes:
      - $HOME/.aws:/root/.aws
      - ./.cdk-out:/output
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:$PWD

networks:
  default:
    name: my-site-network