name: Build and Deploy
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Create .env
        run: touch .env

      - name: Deploy to aws
        run: docker-compose run --rm -e PRODUCTION=true -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -e AWS_DEFAULT_REGION='eu-west-1' infra ./deploy-live.sh

      - name: Build frontend
        run: docker-compose run --rm frontend-vue ./build.sh

      - name: Deploy front end
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master # The branch the action should deploy to.
          folder: frontend-vue/dist # The folder the action should deploy.